export { default as Steps } from 'antd/lib/steps';
import 'antd/lib/steps/style/index.less';
export { default as Button } from 'antd/lib/button';
import 'antd/lib/button/style/index.less';
export { default as Spinner } from 'antd/lib/spin';
import 'antd/lib/spin/style/index.less';
export { default as Message } from 'antd/lib/message';
import 'antd/lib/message/style/index.less';
export { default as Notification } from 'antd/lib/notification';
import 'antd/lib/notification/style/index.less';
export { default as Modal } from 'antd/lib/modal';
import 'antd/lib/modal/style/index.less';
export { default as Collapse } from 'antd/lib/collapse';
import 'antd/lib/collapse/style/index.less';
export { default as Alert } from 'antd/lib/alert';
import 'antd/lib/alert/style/index.less';
export { default as Tabs } from 'antd/lib/tabs';
import 'antd/lib/tabs/style/index.less';
export { default as Avatar } from 'antd/lib/avatar';
import 'antd/lib/avatar/style/index.less';
export { default as Input } from 'antd/lib/Input';
import 'antd/lib/Input/style/index.less';

export { default as Icon } from 'antd/lib/icon';

export { default as TextInput } from './TextInput/TextInput';
export { default as NumberInput } from './NumberInput/NumberInput';
export { default as Select } from './Select/Select';
export { default as TextArea } from './TextArea/TextArea';
export { default as Checkbox } from './Checkbox/Checkbox';
